language: php

php:
  - 5.6
  - 7.0
  - hhvm

install: composer install --dev

after_script:
  - vendor/bin/test-reporter --stdout > codeclimate.json
  - "curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.1.1)' https://codeclimate.com/test_reports"

notifications:
  email: false
  slack:
    secure: kApnwEQNTCm038LDgiHqsPlOpA58GAFQe8yV6tFYHkodS0wfr3gInul/kCr507jEDZDtFlPxy92gwpp9Vg8ckYT3HB1RI2tkVF/k/c2BlI2ca5loQPQtpwplVwgSWu5mqya0ER3GGB7J9VKjNSoLpA99MPyyv1NsAaxvDQ8MEhdndIjNVJC0A5vIeLSkfQpwi60VqoFkXCQ82ZvbTl4eelZaFUKKbVnx7+NmvCOiCrvhNvVnEHHa1quvpqCxhMejIZOMqOy3Ny0cyMKyCAofcspP6BmhXQCT5/fTQQnLp2dVcxVSpZm7HE4uEtoeZ3c9zRGuHQ8RW7sSFpzcanV5v/t8wYYO4wnNZmwU3Vag0z77HKMWa7ybLNddihrf0Z0HEnr/STGnwPTWo+5Y2yhIMIok5riUF1xqhl2yaXe6yyfFfBITlWWgF5OtqIXmV5cNPcrnSoNpCHoegLCKFy//IGG5UmdjdPDOl24Ffb8B6DFHUr2AnZeFXLusfb/eOJssbf7A7qD49rFqVOwKwWDERcZ8qwRTn5nrQYRUdVfKZARDir1DEev17f4/12WS8kqseUBIUYbt5QqCvVleGzB2aRgTnWuvBSb4UtnbOKt4ozkjxFqsniO6XepWcp9uUAyzbhVS6FxACZOhocE+93tg9HFzPouzYpVq5DSyxWg9Rug=
